curl --request GET \
     --url https://api.spotify.com/v1/artists/7tPoZvl7OYT2rQDdzCQpfR/top-tracks?market="ES" \
     -H "Authorization: Bearer  BQD9QEUiycGXGcPTIJfljQScOCVWP16LlPgQd1g88xkjk3ZKIi-JyROTJxZEJhqoK6o3BYulkXpyI6thJOBbIRHx7GUkwOAEoOCoJiff0JgEXUQHMrg"